// <auto-generated />
using System;
using JQuery.Infra.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JQuery.Infra.Repository.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20230308170614_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JQuery.Domain.Entities.Friend", b =>
                {
                    b.Property<Guid>("IdFriend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFRIEND");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FriendName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FRIENDNAME");

                    b.Property<int>("IdState")
                        .HasColumnType("int")
                        .HasColumnName("IDSTATE");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("stateIdState")
                        .HasColumnType("int");

                    b.HasKey("IdFriend");

                    b.HasIndex("FriendName")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("stateIdState");

                    b.ToTable("FRIEND");
                });

            modelBuilder.Entity("JQuery.Domain.Entities.State", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateAcronym")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdState");

                    b.ToTable("State");
                });

            modelBuilder.Entity("JQuery.Domain.Entities.Friend", b =>
                {
                    b.HasOne("JQuery.Domain.Entities.State", "state")
                        .WithMany("Friends")
                        .HasForeignKey("stateIdState");

                    b.Navigation("state");
                });

            modelBuilder.Entity("JQuery.Domain.Entities.State", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
